VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "grilla"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Attribute VB_Ext_KEY = "SavedWithClassBuilder6" ,"Yes"
Attribute VB_Ext_KEY = "Top_Level" ,"Yes"
'
'Option Explicit
'
''donde se ponga grilla, hacer enum para poner nombre a las columnas
'
'
'Public Enum griColTipo
'    griColTXT
'    griColNUM
'    griColCBO
'    griColBIT
'End Enum
'
''Public Sub Grilli.Col()
''
''End Sub
'
'Public Function ColFormat(grilla As Object, Col As Long, tipo As griColTipo, titulo As String, parametro, Optional visible As Boolean = True)
'    If grilla.cols < Col + 1 Then grilla.cols = Col + 1
'
'
'End Function
'
'Public Function borrar(grilla As Object)
'    grilla.rows = 1
'    grilla.rows = 2
'End Function
